# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIv2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(890, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(890, 600))
        MainWindow.setFocusPolicy(QtCore.Qt.WheelFocus)
        MainWindow.setWindowTitle("")
        MainWindow.setStyleSheet("#MainWindow{\n"
"    background-color: rgb(67, 74, 95);\n"
"}\n"
"#hmenu,#kmenu,#fmenu,#tmenu,#close{\n"
"background-color:rgb(67, 74, 95);\n"
"color:rgb(84, 119, 216);\n"
"font: 63 12pt \"Yu Gothic UI Semibold\"\n"
"}\n"
"\n"
"\n"
"#hmenu:hover,#kmenu:hover,#fmenu:hover,#tmenu:hover,#close:hover{\n"
"background-color:rgb(89, 98, 126);\n"
"color:rgb(93, 132, 240);\n"
"font: 63 12pt \"Yu Gothic UI Semibold\"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"#hwidget,#kwidget,#fwidget,#twidget{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(36, 63, 89, 255), stop:0.323864 rgba(47, 82, 116, 255), stop:0.965909 rgba(24, 41, 59, 255), stop:1 rgba(67, 74, 95, 255));\n"
"}\n"
"#close{\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"}\n"
"#close:hover{\n"
"font: 75 14pt \"Comic Sans MS\";\n"
"}\n"
"")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hwidget = QtWidgets.QWidget(self.centralwidget)
        self.hwidget.setGeometry(QtCore.QRect(0, 50, 911, 551))
        self.hwidget.setStyleSheet("#logo_mecatronica{\n"
"border-color: rgb(122, 122, 122);\n"
"}\n"
"#wimg1{\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.3125 rgba(74, 195, 214, 255), stop:1 rgba(33, 143, 177, 255));\n"
" margin-right: 10px;    \n"
"border-radius: 25px;\n"
"    border-style: dashed;\n"
"padding: 2px\n"
"\n"
"}\n"
"\n"
"#wimg2{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0.0852273 rgba(60, 158, 203, 255), stop:1 rgba(15, 92, 130, 255));\n"
"border-radius: 25px;\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"border-left-color:rgb(85, 0, 127);\n"
"border-bottom-color: rgb(255, 0, 0);\n"
"border-right-color:rgb(85, 0, 127);\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(60, 158, 203, 255), stop:1 rgba(15, 92, 130, 255))\n"
"\n"
"}\n"
"#l10,#l20{\n"
"border-width: 2px 0px 0px 2px;\n"
"border-style: groove;\n"
"border-top-right-radius:23px 30px;\n"
"border-bottom-left-radius:23px 30px;\n"
"background-color:qlineargradient(spread:reflect, x1:1, y1:0.472, x2:1, y2:1, stop:0.0795455 rgba(74, 130, 183, 255), stop:0.375 rgba(52, 91, 128, 255), stop:0.659091 rgba(41, 71, 101, 255), stop:1 rgba(56, 96, 138, 255));\n"
"border-color:rgb(36, 63, 89);\n"
"color:rgb(226, 226, 226);\n"
"font: 75 10pt \"Square721 BT\";\n"
"}\n"
"#l10:hover,#l20:hover{\n"
"color:rgb(255, 255, 255);\n"
"background-color:qlineargradient(spread:reflect, x1:1, y1:0.472, x2:1, y2:1, stop:0.0795455 rgba(94, 150, 203, 255), stop:0.375 rgba(72, 111, 158, 255), stop:0.659091 rgba(61, 91, 121, 255), stop:1 rgba(76,116, 158, 255));\n"
"}\n"
"\n"
"")
        self.hwidget.setObjectName("hwidget")
        self.label_20 = QtWidgets.QLabel(self.hwidget)
        self.label_20.setGeometry(QtCore.QRect(50, 250, 301, 231))
        font = QtGui.QFont()
        font.setFamily("ISOCTEUR")
        font.setPointSize(18)
        self.label_20.setFont(font)
        self.label_20.setToolTipDuration(1)
        self.label_20.setStyleSheet("background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1,spread:pad, x40:1, y40:0, x40:1, y40:1 ,stop:0 rgba(81, 81, 81, 255), stop:0.0397727 rgba(58, 58, 58, 255), stop:0.454545 rgba(81, 81, 81, 255), stop:1 rgba(36, 36, 36, 255));\n"
"color:qlineargradient(spread:reflect, x1:0.756, y1:0.755727, x2:1, y2:1, stop:0 rgba(0, 95, 143, 255), stop:1 rgba(0, 170, 255, 255));\n"
"border-radius:20px;")
        self.label_20.setText("")
        self.label_20.setScaledContents(True)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setIndent(1)
        self.label_20.setObjectName("label_20")
        self.label = QtWidgets.QLabel(self.hwidget)
        self.label.setGeometry(QtCore.QRect(80, 290, 121, 31))
        self.label.setStyleSheet("font: 75 16pt \"Square721 BT\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.hwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 340, 201, 31))
        self.label_2.setStyleSheet("font: 75 10pt \"Square721 BT\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.hwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 370, 201, 31))
        self.label_3.setStyleSheet("font: 75 10pt \"Square721 BT\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.hwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 400, 191, 31))
        self.label_4.setStyleSheet("font: 75 10pt \"Square721 BT\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_15 = QtWidgets.QLabel(self.hwidget)
        self.label_15.setGeometry(QtCore.QRect(70, 150, 261, 71))
        self.label_15.setStyleSheet("font: 75 16pt \"Square721 BT\";\n"
"color: rgb(255, 255, 255);")
        self.label_15.setTextFormat(QtCore.Qt.PlainText)
        self.label_15.setObjectName("label_15")
        self.label_27 = QtWidgets.QLabel(self.hwidget)
        self.label_27.setGeometry(QtCore.QRect(240, 50, 91, 91))
        self.label_27.setStyleSheet("font: 75 16pt \"Square721 BT\";\n"
"color: rgb(255, 255, 255);")
        self.label_27.setText("")
        self.label_27.setTextFormat(QtCore.Qt.PlainText)
        self.label_27.setPixmap(QtGui.QPixmap("mecatronica.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_29 = QtWidgets.QLabel(self.hwidget)
        self.label_29.setGeometry(QtCore.QRect(70, 50, 91, 91))
        self.label_29.setStyleSheet("font: 75 16pt \"Square721 BT\";\n"
"color: rgb(255, 255, 255);")
        self.label_29.setText("")
        self.label_29.setTextFormat(QtCore.Qt.PlainText)
        self.label_29.setPixmap(QtGui.QPixmap("logoUNT.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.logo_mecatronica_10 = QtWidgets.QLabel(self.hwidget)
        self.logo_mecatronica_10.setGeometry(QtCore.QRect(680, 310, 141, 141))
        self.logo_mecatronica_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logo_mecatronica_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.logo_mecatronica_10.setLineWidth(0)
        self.logo_mecatronica_10.setMidLineWidth(11)
        self.logo_mecatronica_10.setText("")
        self.logo_mecatronica_10.setPixmap(QtGui.QPixmap("highboost_filtrada.jpg"))
        self.logo_mecatronica_10.setScaledContents(True)
        self.logo_mecatronica_10.setObjectName("logo_mecatronica_10")
        self.logo_mecatronica_3 = QtWidgets.QLabel(self.hwidget)
        self.logo_mecatronica_3.setGeometry(QtCore.QRect(680, 90, 141, 141))
        self.logo_mecatronica_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logo_mecatronica_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.logo_mecatronica_3.setLineWidth(0)
        self.logo_mecatronica_3.setMidLineWidth(11)
        self.logo_mecatronica_3.setText("")
        self.logo_mecatronica_3.setPixmap(QtGui.QPixmap("embossing_papanoel.bmp"))
        self.logo_mecatronica_3.setScaledContents(True)
        self.logo_mecatronica_3.setObjectName("logo_mecatronica_3")
        self.l10 = QtWidgets.QLabel(self.hwidget)
        self.l10.setGeometry(QtCore.QRect(420, 40, 221, 41))
        self.l10.setStyleSheet("")
        self.l10.setFrameShape(QtWidgets.QFrame.Box)
        self.l10.setLineWidth(1)
        self.l10.setTextFormat(QtCore.Qt.PlainText)
        self.l10.setAlignment(QtCore.Qt.AlignCenter)
        self.l10.setObjectName("l10")
        self.l20 = QtWidgets.QLabel(self.hwidget)
        self.l20.setGeometry(QtCore.QRect(420, 250, 221, 41))
        self.l20.setStyleSheet("")
        self.l20.setFrameShape(QtWidgets.QFrame.Box)
        self.l20.setLineWidth(1)
        self.l20.setTextFormat(QtCore.Qt.PlainText)
        self.l20.setAlignment(QtCore.Qt.AlignCenter)
        self.l20.setObjectName("l20")
        self.label_E1_16 = QtWidgets.QLabel(self.hwidget)
        self.label_E1_16.setGeometry(QtCore.QRect(440, 60, 411, 201))
        self.label_E1_16.setStyleSheet("background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(86, 86, 86, 255), stop:0.267045 rgba(60, 60, 60, 255), stop:0.596591 rgba(75, 75, 75, 255), stop:1 rgba(29, 29, 29, 255));\n"
"\n"
"border-style:outset;\n"
"border-width: 1px;\n"
"border-top-color:rgb(65, 65, 65);\n"
"border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(44, 44, 44, 255), stop:0.590909 rgba(95, 95, 95, 255), stop:1 rgba(45, 45, 45, 255));\n"
"border-bottom-color:transparent;\n"
"border-left-color: transparent;\n"
"\n"
"border-bottom-left-radius:30px;\n"
"border-top-right-radius:30px;")
        self.label_E1_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_E1_16.setLineWidth(1)
        self.label_E1_16.setText("")
        self.label_E1_16.setTextFormat(QtCore.Qt.PlainText)
        self.label_E1_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_E1_16.setObjectName("label_E1_16")
        self.label_E1_17 = QtWidgets.QLabel(self.hwidget)
        self.label_E1_17.setGeometry(QtCore.QRect(440, 280, 411, 201))
        self.label_E1_17.setStyleSheet("background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(86, 86, 86, 255), stop:0.267045 rgba(60, 60, 60, 255), stop:0.596591 rgba(75, 75, 75, 255), stop:1 rgba(29, 29, 29, 255));\n"
"\n"
"border-style:outset;\n"
"border-width: 1px;\n"
"border-top-color:rgb(65, 65, 65);\n"
"border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(44, 44, 44, 255), stop:0.590909 rgba(95, 95, 95, 255), stop:1 rgba(45, 45, 45, 255));\n"
"border-bottom-color:transparent;\n"
"border-left-color: transparent;\n"
"\n"
"border-bottom-left-radius:30px;\n"
"border-top-right-radius:30px;")
        self.label_E1_17.setFrameShape(QtWidgets.QFrame.Box)
        self.label_E1_17.setLineWidth(1)
        self.label_E1_17.setText("")
        self.label_E1_17.setTextFormat(QtCore.Qt.PlainText)
        self.label_E1_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_E1_17.setObjectName("label_E1_17")
        self.label_7 = QtWidgets.QLabel(self.hwidget)
        self.label_7.setGeometry(QtCore.QRect(460, 60, 201, 131))
        self.label_7.setStyleSheet("font: 75 10pt \"Square721 BT\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setTextFormat(QtCore.Qt.PlainText)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.hwidget)
        self.label_8.setGeometry(QtCore.QRect(460, 280, 201, 131))
        self.label_8.setStyleSheet("font: 75 10pt \"Square721 BT\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setTextFormat(QtCore.Qt.PlainText)
        self.label_8.setObjectName("label_8")
        self.matrizLabel_3 = QtWidgets.QLabel(self.hwidget)
        self.matrizLabel_3.setGeometry(QtCore.QRect(490, 140, 271, 131))
        self.matrizLabel_3.setStyleSheet("color:rgb(195, 195, 195);\n"
"\n"
"font: 10pt \"Fixedsys\";\n"
"font: 75 9pt \"Courier New\";")
        self.matrizLabel_3.setObjectName("matrizLabel_3")
        self.matrizLabel_4 = QtWidgets.QLabel(self.hwidget)
        self.matrizLabel_4.setGeometry(QtCore.QRect(460, 400, 271, 41))
        self.matrizLabel_4.setStyleSheet("color:rgb(195, 195, 195);\n"
"\n"
"font: 10pt \"Fixedsys\";\n"
"font: 75 9pt \"Courier New\";")
        self.matrizLabel_4.setObjectName("matrizLabel_4")
        self.label_20.raise_()
        self.label_E1_17.raise_()
        self.label_E1_16.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_15.raise_()
        self.label_27.raise_()
        self.label_29.raise_()
        self.logo_mecatronica_10.raise_()
        self.logo_mecatronica_3.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.matrizLabel_3.raise_()
        self.matrizLabel_4.raise_()
        self.l10.raise_()
        self.l20.raise_()
        self.kmenu = QtWidgets.QPushButton(self.centralwidget)
        self.kmenu.setGeometry(QtCore.QRect(170, 0, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        font.setKerning(False)
        self.kmenu.setFont(font)
        self.kmenu.setMouseTracking(True)
        self.kmenu.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.kmenu.setAcceptDrops(False)
        self.kmenu.setToolTipDuration(-1)
        self.kmenu.setAutoFillBackground(False)
        self.kmenu.setCheckable(False)
        self.kmenu.setAutoRepeat(False)
        self.kmenu.setDefault(False)
        self.kmenu.setFlat(False)
        self.kmenu.setObjectName("kmenu")
        self.fmenu = QtWidgets.QPushButton(self.centralwidget)
        self.fmenu.setGeometry(QtCore.QRect(340, 0, 171, 51))
        self.fmenu.setMouseTracking(True)
        self.fmenu.setAutoFillBackground(False)
        self.fmenu.setCheckable(False)
        self.fmenu.setDefault(False)
        self.fmenu.setObjectName("fmenu")
        self.hmenu = QtWidgets.QPushButton(self.centralwidget)
        self.hmenu.setGeometry(QtCore.QRect(0, 0, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        font.setKerning(False)
        self.hmenu.setFont(font)
        self.hmenu.setMouseTracking(True)
        self.hmenu.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.hmenu.setAcceptDrops(False)
        self.hmenu.setToolTipDuration(9)
        self.hmenu.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/lenovo/.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hmenu.setIcon(icon)
        self.hmenu.setCheckable(False)
        self.hmenu.setAutoRepeat(False)
        self.hmenu.setDefault(False)
        self.hmenu.setFlat(False)
        self.hmenu.setObjectName("hmenu")
        self.fwidget = QtWidgets.QWidget(self.centralwidget)
        self.fwidget.setGeometry(QtCore.QRect(0, 50, 891, 561))
        self.fwidget.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"    border: 1px outset rgb(108, 108, 108);\n"
"}\n"
"\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 1px; /* move to the right by 5px */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0.00568182, y2:1, stop:0 rgba(106, 106, 106, 255), stop:0.278409 rgba(156, 156, 156, 255), stop:1 rgba(106, 106, 106, 255));\n"
"    color:rgb(255, 255, 255);\n"
"    border: 2px solid  rgb(142, 142, 142);\n"
"    \n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    min-width: 20ex;\n"
"    padding: 6px;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:0.00568182, y2:1, stop:0 rgba(61, 61, 61, 255), stop:0.5 rgba(133, 133, 133, 255), stop:1 rgba(61, 61, 61, 255))\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: rgb(77, 77, 77);\n"
"    border-bottom-color: rgb(108, 108, 108); \n"
"\n"
"}\n"
"\n"
"#l4, #l5{\n"
"border-width: 2px 0px 0px 2px;\n"
"border-style: groove;\n"
"border-top-right-radius:23px 30px;\n"
"border-bottom-left-radius:23px 30px;\n"
"background-color:qlineargradient(spread:reflect, x1:1, y1:0.472, x2:1, y2:1, stop:0.0795455 rgba(74, 130, 183, 255), stop:0.375 rgba(52, 91, 128, 255), stop:0.659091 rgba(41, 71, 101, 255), stop:1 rgba(56, 96, 138, 255));\n"
"border-color:rgb(36, 63, 89);\n"
"color:rgb(226, 226, 226);\n"
"font: 75 10pt \"Square721 BT\";\n"
"}\n"
"#l4:hover,#l5:hover{\n"
"color:rgb(255, 255, 255);\n"
"background-color:qlineargradient(spread:reflect, x1:1, y1:0.472, x2:1, y2:1, stop:0.0795455 rgba(94, 150, 203, 255), stop:0.375 rgba(72, 111, 158, 255), stop:0.659091 rgba(61, 91, 121, 255), stop:1 rgba(76,116, 158, 255));\n"
"}\n"
"\n"
"\n"
"\n"
"#update_f:!pressed{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(52, 52, 52, 255), stop:0.0681818 rgba(38, 38, 38, 255), stop:0.193182 rgba(65, 65, 65, 255), stop:1 rgba(2, 2, 2, 255));\n"
"font: 75 8pt \"Square721 BT\";\n"
"color: rgb(29, 145, 203);\n"
"\n"
"border-radius:10px;\n"
"border-width:1px;\n"
"border-style:inset;\n"
"border-top-color: rgb(72, 72, 72);\n"
"border-right-color:rgb(106, 106, 106);\n"
"border-bottom-color: rgb(106, 106, 106);\n"
"border-left-color: rgb(72, 72, 72);\n"
"}\n"
"#update_f:hover{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(62, 62, 62, 255), stop:0.0681818 rgba(48, 48, 48, 255), stop:0.193182 rgba(75, 75, 75, 255), stop:1 rgba(22, 22, 22, 255));\n"
"}\n"
"#update_f:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(9, 9, 9, 255), stop:0.5 rgba(65, 65, 65, 255), stop:1 rgba(9, 9, 9, 255));\n"
"font: 75 8pt \"Square721 BT\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"border-width:1px;\n"
"border-style:inset;\n"
"border-top-color: rgb(72, 72, 72);\n"
"border-right-color:rgb(106, 106, 106);\n"
"border-bottom-color: rgb(106, 106, 106);\n"
"border-left-color: rgb(72, 72, 72);\n"
"}\n"
"\n"
"#abutton_2:!pressed,#rbutton_2:!pressed, #sbutton_2:!pressed{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(47, 47, 47, 255), stop:0.329545 rgba(72, 72, 72, 255), stop:1 rgba(47, 47, 47, 255));\n"
"font: 75 8pt \"Square721 BT\";\n"
"color:rgb(255, 255, 255);\n"
"\n"
"border-radius:10px;\n"
"border-width:1px;\n"
"border-style:inset;\n"
"border-top-color: rgb(72, 72, 72);\n"
"border-right-color:rgb(106, 106, 106);\n"
"border-bottom-color: rgb(76, 76, 76);\n"
"border-left-color: rgb(72, 72, 72);\n"
"}\n"
"#abutton_2:pressed,#rbutton_2:pressed,#sbutton_2:pressed{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(68, 68, 68, 255), stop:0.494318 rgba(106, 106, 106, 255), stop:1 rgba(63, 63, 63, 255));\n"
"font: 75 8pt \"Square721 BT\";\n"
"color: rgb(200, 200, 200);\n"
"border-radius:10px;\n"
"border-width:1px;\n"
"border-style:inset;\n"
"border-top-color: rgb(72, 72, 72);\n"
"border-right-color:rgb(106, 106, 106);\n"
"border-bottom-color: rgb(106, 106, 106);\n"
"border-left-color: rgb(72, 72, 72);\n"
"}\n"
"#abutton_2:hover,#rbutton_2:hover, #sbutton_2:hover{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(52, 52, 52, 255), stop:0.329545 rgba(90, 90, 90, 255), stop:1 rgba(52, 52, 52, 255))\n"
"}\n"
"\n"
"#slider_2,#slider_3,#slider_4{margin: 0px;}\n"
"#slider_2::groove:horizontal,#slider_3::groove:horizontal,#slider_4::groove:horizontal {\n"
"    border-radius: 5px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color:rgb(149, 149, 149);\n"
"}\n"
"#slider_2::groove:horizontal:hover,#slider_3::groove:horizontal:hover,#slider_4::groove:horizontal:hover{\n"
"    background-color:rgb(180, 180, 180);\n"
"}\n"
"#slider_2:handle:horizontal,#slider_3:handle:horizontal,#slider_4:handle:horizontal{\n"
"    border:none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-radius:5px;\n"
"    margin:0px;\n"
"    background-color:rgb(59, 103, 144);\n"
"}\n"
"#slider_2:handle:horizontal:hover,#slider_3:handle:horizontal:hover,#slider_4:handle:horizontal:hover{\n"
"    background-color:rgb(59, 103, 144);\n"
"}\n"
"#slider_2:handle:horizontal:pressed,#slider_4:handle:horizontal:pressed,#slider_4:handle:horizontal:pressed{\n"
"    background-color:rgb(89, 133, 174);\n"
"}\n"
"\n"
"#combo_2{\n"
"    background-color:rgb(149, 149, 149);\n"
"border-width:2px;\n"
"border-style:inset;\n"
"border-top-color: rgb(182, 182, 182);\n"
"border-right-color: transparent;\n"
"border-bottom-color: rgb(82, 82, 82);\n"
"border-left-color: rgb(100, 100, 100);\n"
"color:white;\n"
"font: 75 9pt \"Square721 BT\";\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"}\n"
"#combo_2:hover{\n"
"background-color:rgb(160, 160, 160);\n"
"border-width:2px;\n"
"border-style:inset;\n"
"border-top-color: rgb(182, 182, 182);\n"
"border-right-color: transparent;\n"
"border-bottom-color: rgb(82, 82, 82);\n"
"border-left-color: rgb(100, 100, 100);\n"
"color:white;\n"
"font: 75 9pt \"Square721 BT\";\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"")
        self.fwidget.setObjectName("fwidget")
        self.tabwidget_2 = QtWidgets.QTabWidget(self.fwidget)
        self.tabwidget_2.setGeometry(QtCore.QRect(30, 50, 351, 291))
        self.tabwidget_2.setStyleSheet("")
        self.tabwidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabwidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabwidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabwidget_2.setUsesScrollButtons(False)
        self.tabwidget_2.setDocumentMode(False)
        self.tabwidget_2.setTabsClosable(False)
        self.tabwidget_2.setMovable(True)
        self.tabwidget_2.setTabBarAutoHide(False)
        self.tabwidget_2.setObjectName("tabwidget_2")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.imgdef_2 = QtWidgets.QLabel(self.tab_7)
        self.imgdef_2.setGeometry(QtCore.QRect(0, 0, 351, 261))
        self.imgdef_2.setStyleSheet("background-color: rgb(164, 164, 164);")
        self.imgdef_2.setFrameShape(QtWidgets.QFrame.Box)
        self.imgdef_2.setLineWidth(1)
        self.imgdef_2.setText("")
        self.imgdef_2.setTextFormat(QtCore.Qt.PlainText)
        self.imgdef_2.setScaledContents(True)
        self.imgdef_2.setAlignment(QtCore.Qt.AlignCenter)
        self.imgdef_2.setObjectName("imgdef_2")
        self.tabwidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.imgfilt_2 = QtWidgets.QLabel(self.tab_8)
        self.imgfilt_2.setGeometry(QtCore.QRect(0, 0, 351, 261))
        self.imgfilt_2.setStyleSheet("background-color: rgb(164, 164, 164);")
        self.imgfilt_2.setFrameShape(QtWidgets.QFrame.Box)
        self.imgfilt_2.setLineWidth(1)
        self.imgfilt_2.setText("")
        self.imgfilt_2.setTextFormat(QtCore.Qt.PlainText)
        self.imgfilt_2.setScaledContents(True)
        self.imgfilt_2.setAlignment(QtCore.Qt.AlignCenter)
        self.imgfilt_2.setObjectName("imgfilt_2")
        self.tabwidget_2.addTab(self.tab_8, "Imagen Filtrada")
        self.l5 = QtWidgets.QLabel(self.fwidget)
        self.l5.setGeometry(QtCore.QRect(420, 40, 151, 41))
        self.l5.setStyleSheet("")
        self.l5.setFrameShape(QtWidgets.QFrame.Box)
        self.l5.setLineWidth(1)
        self.l5.setTextFormat(QtCore.Qt.PlainText)
        self.l5.setAlignment(QtCore.Qt.AlignCenter)
        self.l5.setObjectName("l5")
        self.sbutton_2 = QtWidgets.QPushButton(self.fwidget)
        self.sbutton_2.setGeometry(QtCore.QRect(270, 370, 111, 31))
        self.sbutton_2.setObjectName("sbutton_2")
        self.rbutton_2 = QtWidgets.QPushButton(self.fwidget)
        self.rbutton_2.setGeometry(QtCore.QRect(150, 370, 111, 31))
        self.rbutton_2.setObjectName("rbutton_2")
        self.update_f = QtWidgets.QPushButton(self.fwidget)
        self.update_f.setGeometry(QtCore.QRect(690, 90, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Square721 BT")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.update_f.setFont(font)
        self.update_f.setStyleSheet("")
        self.update_f.setDefault(False)
        self.update_f.setFlat(False)
        self.update_f.setObjectName("update_f")
        self.combo_2 = QtWidgets.QComboBox(self.fwidget)
        self.combo_2.setGeometry(QtCore.QRect(470, 100, 201, 21))
        self.combo_2.setStyleSheet("")
        self.combo_2.setObjectName("combo_2")
        self.combo_2.addItem("")
        self.combo_2.addItem("")
        self.combo_2.addItem("")
        self.combo_2.addItem("")
        self.combo_2.addItem("")
        self.combo_2.addItem("")
        self.label_E1_15 = QtWidgets.QLabel(self.fwidget)
        self.label_E1_15.setGeometry(QtCore.QRect(450, 60, 411, 111))
        self.label_E1_15.setStyleSheet("background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(86, 86, 86, 255), stop:0.267045 rgba(60, 60, 60, 255), stop:0.596591 rgba(75, 75, 75, 255), stop:1 rgba(29, 29, 29, 255));\n"
"\n"
"border-style:outset;\n"
"border-width: 1px;\n"
"border-top-color:rgb(65, 65, 65);\n"
"border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(44, 44, 44, 255), stop:0.590909 rgba(95, 95, 95, 255), stop:1 rgba(45, 45, 45, 255));\n"
"border-bottom-color:transparent;\n"
"border-left-color: transparent;\n"
"\n"
"border-bottom-left-radius:30px;\n"
"border-top-right-radius:30px;")
        self.label_E1_15.setFrameShape(QtWidgets.QFrame.Box)
        self.label_E1_15.setLineWidth(1)
        self.label_E1_15.setText("")
        self.label_E1_15.setTextFormat(QtCore.Qt.PlainText)
        self.label_E1_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_E1_15.setObjectName("label_E1_15")
        self.abutton_2 = QtWidgets.QPushButton(self.fwidget)
        self.abutton_2.setGeometry(QtCore.QRect(30, 370, 111, 31))
        self.abutton_2.setObjectName("abutton_2")
        self.tabwidget_2.raise_()
        self.label_E1_15.raise_()
        self.l5.raise_()
        self.sbutton_2.raise_()
        self.rbutton_2.raise_()
        self.update_f.raise_()
        self.combo_2.raise_()
        self.abutton_2.raise_()
        self.kwidget = QtWidgets.QWidget(self.centralwidget)
        self.kwidget.setGeometry(QtCore.QRect(0, 50, 891, 561))
        font = QtGui.QFont()
        font.setKerning(False)
        self.kwidget.setFont(font)
        self.kwidget.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"    border: 1px outset rgb(108, 108, 108);\n"
"}\n"
"\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 1px; /* move to the right by 5px */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0.00568182, y2:1, stop:0 rgba(106, 106, 106, 255), stop:0.278409 rgba(156, 156, 156, 255), stop:1 rgba(106, 106, 106, 255));\n"
"    color:rgb(255, 255, 255);\n"
"    border: 2px solid  rgb(142, 142, 142);\n"
"    \n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    min-width: 20ex;\n"
"    padding: 6px;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:0.00568182, y2:1, stop:0 rgba(61, 61, 61, 255), stop:0.5 rgba(133, 133, 133, 255), stop:1 rgba(61, 61, 61, 255))\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: rgb(77, 77, 77);\n"
"    border-bottom-color: rgb(108, 108, 108); \n"
"\n"
"}\n"
"\n"
"#l1, #l2, #l3{\n"
"border-width: 2px 0px 0px 2px;\n"
"border-style: groove;\n"
"border-top-right-radius:23px 30px;\n"
"border-bottom-left-radius:23px 30px;\n"
"background-color:qlineargradient(spread:reflect, x1:1, y1:0.472, x2:1, y2:1, stop:0.0795455 rgba(74, 130, 183, 255), stop:0.375 rgba(52, 91, 128, 255), stop:0.659091 rgba(41, 71, 101, 255), stop:1 rgba(56, 96, 138, 255));\n"
"border-color:rgb(36, 63, 89);\n"
"color:rgb(226, 226, 226);\n"
"font: 75 10pt \"Square721 BT\";\n"
"}\n"
"#l1:hover,#l2:hover,#l3:hover{\n"
"color:rgb(255, 255, 255);\n"
"background-color:qlineargradient(spread:reflect, x1:1, y1:0.472, x2:1, y2:1, stop:0.0795455 rgba(94, 150, 203, 255), stop:0.375 rgba(72, 111, 158, 255), stop:0.659091 rgba(61, 91, 121, 255), stop:1 rgba(76,116, 158, 255));\n"
"}\n"
"\n"
"#update_p:!pressed,#update_d:!pressed{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(52, 52, 52, 255), stop:0.0681818 rgba(38, 38, 38, 255), stop:0.193182 rgba(65, 65, 65, 255), stop:1 rgba(2, 2, 2, 255));\n"
"font: 75 8pt \"Square721 BT\";\n"
"color: rgb(29, 145, 203);\n"
"\n"
"border-radius:10px;\n"
"border-width:1px;\n"
"border-style:inset;\n"
"border-top-color: rgb(72, 72, 72);\n"
"border-right-color:rgb(106, 106, 106);\n"
"border-bottom-color: rgb(106, 106, 106);\n"
"border-left-color: rgb(72, 72, 72);\n"
"}\n"
"#update_p:hover,#update_d:hover{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(62, 62, 62, 255), stop:0.0681818 rgba(48, 48, 48, 255), stop:0.193182 rgba(75, 75, 75, 255), stop:1 rgba(22, 22, 22, 255));\n"
"}\n"
"#update_p:pressed,#update_d:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(9, 9, 9, 255), stop:0.5 rgba(65, 65, 65, 255), stop:1 rgba(9, 9, 9, 255));\n"
"font: 75 8pt \"Square721 BT\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"border-width:1px;\n"
"border-style:inset;\n"
"border-top-color: rgb(72, 72, 72);\n"
"border-right-color:rgb(106, 106, 106);\n"
"border-bottom-color: rgb(106, 106, 106);\n"
"border-left-color: rgb(72, 72, 72);\n"
"}\n"
"\n"
"#abutton:!pressed,#rbutton:!pressed,#sbutton:!pressed{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(47, 47, 47, 255), stop:0.329545 rgba(72, 72, 72, 255), stop:1 rgba(47, 47, 47, 255));\n"
"font: 75 8pt \"Square721 BT\";\n"
"color:rgb(255, 255, 255);\n"
"\n"
"border-radius:10px;\n"
"border-width:1px;\n"
"border-style:inset;\n"
"border-top-color: rgb(72, 72, 72);\n"
"border-right-color:rgb(106, 106, 106);\n"
"border-bottom-color: rgb(76, 76, 76);\n"
"border-left-color: rgb(72, 72, 72);\n"
"}\n"
"#abutton:pressed,#rbutton:pressed,#sbutton:pressed{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(68, 68, 68, 255), stop:0.494318 rgba(106, 106, 106, 255), stop:1 rgba(63, 63, 63, 255));\n"
"font: 75 8pt \"Square721 BT\";\n"
"color: rgb(200, 200, 200);\n"
"border-radius:10px;\n"
"border-width:1px;\n"
"border-style:inset;\n"
"border-top-color: rgb(72, 72, 72);\n"
"border-right-color:rgb(106, 106, 106);\n"
"border-bottom-color: rgb(106, 106, 106);\n"
"border-left-color: rgb(72, 72, 72);\n"
"}\n"
"#abutton:hover,#rbutton:hover, #sbutton:hover{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(52, 52, 52, 255), stop:0.329545 rgba(90, 90, 90, 255), stop:1 rgba(52, 52, 52, 255))\n"
"}\n"
"\n"
"#slider{margin: 0px;}\n"
"#slider::groove:horizontal {\n"
"    border-radius: 5px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color:rgb(149, 149, 149);\n"
"}\n"
"#slider::groove:horizontal:hover{\n"
"    background-color:rgb(180, 180, 180);\n"
"}\n"
"#slider:handle:horizontal {\n"
"    border:none;\n"
"    height: 10px;\n"
"    width: 20px;\n"
"    border-radius:5px;\n"
"    margin:0px;\n"
"    background-color:rgb(59, 103, 144);\n"
"}\n"
"#slider:handle:horizontal:hover{\n"
"    background-color:rgb(59, 103, 144);\n"
"}\n"
"#slider:handle:horizontal:pressed {\n"
"    background-color:rgb(89, 133, 174);\n"
"}\n"
"\n"
"\n"
"#lineedit{\n"
"background-color:rgb(149, 149, 149);\n"
"border-width:2px;\n"
"border-style:inset;\n"
"border-top-color: rgb(182, 182, 182);\n"
"border-right-color: transparent;\n"
"border-bottom-color: rgb(82, 82, 82);\n"
"border-left-color: rgb(100, 100, 100);\n"
"color:white;\n"
"font: 75 9pt \"Square721 BT\";\n"
"font: 8pt \"MS Shell Dlg 2\";}\n"
"#lineedit:hover{\n"
"background-color:rgb(160, 160, 160)\n"
"}\n"
"#combo{\n"
"    background-color:rgb(149, 149, 149);\n"
"border-width:2px;\n"
"border-style:inset;\n"
"border-top-color: rgb(182, 182, 182);\n"
"border-right-color: transparent;\n"
"border-bottom-color: rgb(82, 82, 82);\n"
"border-left-color: rgb(100, 100, 100);\n"
"color:white;\n"
"font: 75 9pt \"Square721 BT\";\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"}\n"
"#combo:hover{\n"
"background-color:rgb(160, 160, 160);\n"
"border-width:2px;\n"
"border-style:inset;\n"
"border-top-color: rgb(182, 182, 182);\n"
"border-right-color: transparent;\n"
"border-bottom-color: rgb(82, 82, 82);\n"
"border-left-color: rgb(100, 100, 100);\n"
"color:white;\n"
"font: 75 9pt \"Square721 BT\";\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"}")
        self.kwidget.setObjectName("kwidget")
        self.sbutton = QtWidgets.QPushButton(self.kwidget)
        self.sbutton.setGeometry(QtCore.QRect(270, 370, 111, 31))
        self.sbutton.setObjectName("sbutton")
        self.lineedit = QtWidgets.QLineEdit(self.kwidget)
        self.lineedit.setGeometry(QtCore.QRect(470, 310, 201, 31))
        self.lineedit.setStyleSheet("")
        self.lineedit.setInputMask("")
        self.lineedit.setText("")
        self.lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineedit.setObjectName("lineedit")
        self.tabwidget = QtWidgets.QTabWidget(self.kwidget)
        self.tabwidget.setGeometry(QtCore.QRect(30, 50, 351, 291))
        self.tabwidget.setStyleSheet("")
        self.tabwidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabwidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabwidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabwidget.setUsesScrollButtons(False)
        self.tabwidget.setDocumentMode(False)
        self.tabwidget.setTabsClosable(False)
        self.tabwidget.setMovable(True)
        self.tabwidget.setTabBarAutoHide(False)
        self.tabwidget.setObjectName("tabwidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.imgdef = QtWidgets.QLabel(self.tab_1)
        self.imgdef.setGeometry(QtCore.QRect(0, 0, 351, 261))
        self.imgdef.setStyleSheet("background-color: rgb(164, 164, 164);")
        self.imgdef.setFrameShape(QtWidgets.QFrame.Box)
        self.imgdef.setLineWidth(1)
        self.imgdef.setText("")
        self.imgdef.setTextFormat(QtCore.Qt.PlainText)
        self.imgdef.setScaledContents(True)
        self.imgdef.setAlignment(QtCore.Qt.AlignCenter)
        self.imgdef.setObjectName("imgdef")
        self.tabwidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.imgfilt = QtWidgets.QLabel(self.tab_2)
        self.imgfilt.setGeometry(QtCore.QRect(0, 0, 351, 261))
        self.imgfilt.setStyleSheet("background-color: rgb(164, 164, 164);")
        self.imgfilt.setFrameShape(QtWidgets.QFrame.Box)
        self.imgfilt.setLineWidth(1)
        self.imgfilt.setText("")
        self.imgfilt.setTextFormat(QtCore.Qt.PlainText)
        self.imgfilt.setScaledContents(True)
        self.imgfilt.setAlignment(QtCore.Qt.AlignCenter)
        self.imgfilt.setWordWrap(False)
        self.imgfilt.setObjectName("imgfilt")
        self.tabwidget.addTab(self.tab_2, "Imagen Filtrada")
        self.rbutton = QtWidgets.QPushButton(self.kwidget)
        self.rbutton.setGeometry(QtCore.QRect(150, 370, 111, 31))
        self.rbutton.setObjectName("rbutton")
        self.l1 = QtWidgets.QLabel(self.kwidget)
        self.l1.setGeometry(QtCore.QRect(420, 40, 151, 41))
        self.l1.setStyleSheet("")
        self.l1.setFrameShape(QtWidgets.QFrame.Box)
        self.l1.setLineWidth(1)
        self.l1.setTextFormat(QtCore.Qt.PlainText)
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.update_p = QtWidgets.QPushButton(self.kwidget)
        self.update_p.setGeometry(QtCore.QRect(690, 300, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Square721 BT")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.update_p.setFont(font)
        self.update_p.setStyleSheet("")
        self.update_p.setDefault(False)
        self.update_p.setFlat(False)
        self.update_p.setObjectName("update_p")
        self.combo = QtWidgets.QComboBox(self.kwidget)
        self.combo.setGeometry(QtCore.QRect(470, 440, 201, 21))
        self.combo.setStyleSheet("")
        self.combo.setObjectName("combo")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.update_d = QtWidgets.QPushButton(self.kwidget)
        self.update_d.setGeometry(QtCore.QRect(690, 440, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Square721 BT")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.update_d.setFont(font)
        self.update_d.setStyleSheet("")
        self.update_d.setDefault(False)
        self.update_d.setFlat(False)
        self.update_d.setObjectName("update_d")
        self.matrizLabel = QtWidgets.QLabel(self.kwidget)
        self.matrizLabel.setGeometry(QtCore.QRect(490, 90, 331, 121))
        self.matrizLabel.setStyleSheet("color:rgb(195, 195, 195);\n"
"\n"
"font: 10pt \"Fixedsys\";\n"
"font: 75 13pt \"Courier New\";")
        self.matrizLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.matrizLabel.setObjectName("matrizLabel")
        self.label_E1_10 = QtWidgets.QLabel(self.kwidget)
        self.label_E1_10.setGeometry(QtCore.QRect(450, 60, 411, 171))
        self.label_E1_10.setStyleSheet("background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1,spread:pad, x40:1, y40:0, x40:1, y40:1 ,stop:0 rgba(81, 81, 81, 255), stop:0.0397727 rgba(58, 58, 58, 255), stop:0.454545 rgba(81, 81, 81, 255), stop:1 rgba(36, 36, 36, 255));\n"
"color: qlineargradient(spread:reflect, x1:0.834, y1:0.801682, x2:0.960452, y2:0.932, stop:0 rgba(247, 255, 250, 255), stop:0.903955 rgba(180, 180, 180, 255));\n"
"\n"
"border-bottom-left-radius:30px;\n"
"border-top-right-radius:30px;")
        self.label_E1_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_E1_10.setLineWidth(1)
        self.label_E1_10.setText("")
        self.label_E1_10.setTextFormat(QtCore.Qt.PlainText)
        self.label_E1_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_E1_10.setObjectName("label_E1_10")
        self.label_E1_12 = QtWidgets.QLabel(self.kwidget)
        self.label_E1_12.setGeometry(QtCore.QRect(450, 280, 411, 91))
        self.label_E1_12.setStyleSheet("background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(86, 86, 86, 255), stop:0.267045 rgba(60, 60, 60, 255), stop:0.596591 rgba(75, 75, 75, 255), stop:1 rgba(29, 29, 29, 255));\n"
"\n"
"border-style:outset;\n"
"border-width: 1px;\n"
"border-top-color:rgb(65, 65, 65);\n"
"border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(44, 44, 44, 255), stop:0.590909 rgba(95, 95, 95, 255), stop:1 rgba(45, 45, 45, 255));\n"
"border-bottom-color:transparent;\n"
"border-left-color: transparent;\n"
"\n"
"border-bottom-left-radius:30px;\n"
"border-top-right-radius:30px;")
        self.label_E1_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_E1_12.setLineWidth(1)
        self.label_E1_12.setText("")
        self.label_E1_12.setTextFormat(QtCore.Qt.PlainText)
        self.label_E1_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_E1_12.setObjectName("label_E1_12")
        self.label_E1_13 = QtWidgets.QLabel(self.kwidget)
        self.label_E1_13.setGeometry(QtCore.QRect(450, 410, 411, 111))
        self.label_E1_13.setStyleSheet("background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(86, 86, 86, 255), stop:0.267045 rgba(60, 60, 60, 255), stop:0.596591 rgba(75, 75, 75, 255), stop:1 rgba(29, 29, 29, 255));\n"
"\n"
"border-style:outset;\n"
"border-width: 1px;\n"
"border-top-color:rgb(52, 52, 52);\n"
"border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(44, 44, 44, 255), stop:0.590909 rgba(95, 95, 95, 255), stop:1 rgba(45, 45, 45, 255));\n"
"border-bottom-color:transparent;\n"
"border-left-color: transparent;\n"
"\n"
"border-bottom-left-radius:30px;\n"
"border-top-right-radius:30px;")
        self.label_E1_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_E1_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_E1_13.setLineWidth(6)
        self.label_E1_13.setText("")
        self.label_E1_13.setTextFormat(QtCore.Qt.PlainText)
        self.label_E1_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_E1_13.setObjectName("label_E1_13")
        self.l2 = QtWidgets.QLabel(self.kwidget)
        self.l2.setGeometry(QtCore.QRect(420, 250, 151, 41))
        self.l2.setStyleSheet("")
        self.l2.setFrameShape(QtWidgets.QFrame.Box)
        self.l2.setLineWidth(1)
        self.l2.setTextFormat(QtCore.Qt.PlainText)
        self.l2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2.setObjectName("l2")
        self.l3 = QtWidgets.QLabel(self.kwidget)
        self.l3.setGeometry(QtCore.QRect(420, 390, 151, 41))
        self.l3.setStyleSheet("")
        self.l3.setFrameShape(QtWidgets.QFrame.Box)
        self.l3.setLineWidth(1)
        self.l3.setTextFormat(QtCore.Qt.PlainText)
        self.l3.setAlignment(QtCore.Qt.AlignCenter)
        self.l3.setObjectName("l3")
        self.slider = QtWidgets.QSlider(self.kwidget)
        self.slider.setGeometry(QtCore.QRect(470, 480, 201, 21))
        self.slider.setMinimum(1)
        self.slider.setMaximum(100)
        self.slider.setSingleStep(1)
        self.slider.setPageStep(20)
        self.slider.setTracking(True)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setInvertedAppearance(False)
        self.slider.setInvertedControls(False)
        self.slider.setObjectName("slider")
        self.abutton = QtWidgets.QPushButton(self.kwidget)
        self.abutton.setGeometry(QtCore.QRect(30, 370, 111, 31))
        self.abutton.setObjectName("abutton")
        self.tabwidget.raise_()
        self.label_E1_13.raise_()
        self.label_E1_12.raise_()
        self.label_E1_10.raise_()
        self.sbutton.raise_()
        self.lineedit.raise_()
        self.rbutton.raise_()
        self.l1.raise_()
        self.update_p.raise_()
        self.combo.raise_()
        self.update_d.raise_()
        self.matrizLabel.raise_()
        self.l2.raise_()
        self.l3.raise_()
        self.slider.raise_()
        self.abutton.raise_()
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-40, 49, 931, 1))
        self.line.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.close = QtWidgets.QPushButton(self.centralwidget)
        self.close.setGeometry(QtCore.QRect(840, 0, 51, 51))
        self.close.setMouseTracking(True)
        self.close.setAutoFillBackground(False)
        self.close.setCheckable(False)
        self.close.setDefault(False)
        self.close.setObjectName("close")
        self.tmenu = QtWidgets.QPushButton(self.centralwidget)
        self.tmenu.setGeometry(QtCore.QRect(510, 0, 171, 51))
        self.tmenu.setMouseTracking(True)
        self.tmenu.setAutoFillBackground(False)
        self.tmenu.setCheckable(False)
        self.tmenu.setDefault(False)
        self.tmenu.setObjectName("tmenu")
        self.twidget = QtWidgets.QWidget(self.centralwidget)
        self.twidget.setGeometry(QtCore.QRect(0, 50, 891, 561))
        self.twidget.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"    border: 1px outset rgb(108, 108, 108);\n"
"}\n"
"\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 1px; /* move to the right by 5px */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0.00568182, y2:1, stop:0 rgba(106, 106, 106, 255), stop:0.278409 rgba(156, 156, 156, 255), stop:1 rgba(106, 106, 106, 255));\n"
"    color:rgb(255, 255, 255);\n"
"    border: 2px solid  rgb(142, 142, 142);\n"
"    \n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    min-width: 20ex;\n"
"    padding: 6px;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:0.00568182, y2:1, stop:0 rgba(61, 61, 61, 255), stop:0.5 rgba(133, 133, 133, 255), stop:1 rgba(61, 61, 61, 255))\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: rgb(77, 77, 77);\n"
"    border-bottom-color: rgb(108, 108, 108); \n"
"\n"
"}\n"
"\n"
"#l21, #l22, #l23{\n"
"border-width: 2px 0px 0px 2px;\n"
"border-style: groove;\n"
"border-top-right-radius:23px 30px;\n"
"border-bottom-left-radius:23px 30px;\n"
"background-color:qlineargradient(spread:reflect, x1:1, y1:0.472, x2:1, y2:1, stop:0.0795455 rgba(74, 130, 183, 255), stop:0.375 rgba(52, 91, 128, 255), stop:0.659091 rgba(41, 71, 101, 255), stop:1 rgba(56, 96, 138, 255));\n"
"border-color:rgb(36, 63, 89);\n"
"color:rgb(226, 226, 226);\n"
"font: 75 10pt \"Square721 BT\";\n"
"}\n"
"#l21:hover,#l22:hover,#l23:hover{\n"
"color:rgb(255, 255, 255);\n"
"background-color:qlineargradient(spread:reflect, x1:1, y1:0.472, x2:1, y2:1, stop:0.0795455 rgba(94, 150, 203, 255), stop:0.375 rgba(72, 111, 158, 255), stop:0.659091 rgba(61, 91, 121, 255), stop:1 rgba(76,116, 158, 255));\n"
"}\n"
"\n"
"#update_t1:!pressed{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(52, 52, 52, 255), stop:0.0681818 rgba(38, 38, 38, 255), stop:0.193182 rgba(65, 65, 65, 255), stop:1 rgba(2, 2, 2, 255));\n"
"font: 75 8pt \"Square721 BT\";\n"
"color: rgb(29, 145, 203);\n"
"\n"
"border-radius:10px;\n"
"border-width:1px;\n"
"border-style:inset;\n"
"border-top-color: rgb(72, 72, 72);\n"
"border-right-color:rgb(106, 106, 106);\n"
"border-bottom-color: rgb(106, 106, 106);\n"
"border-left-color: rgb(72, 72, 72);\n"
"}\n"
"#update_t1:hover{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(62, 62, 62, 255), stop:0.0681818 rgba(48, 48, 48, 255), stop:0.193182 rgba(75, 75, 75, 255), stop:1 rgba(22, 22, 22, 255));\n"
"}\n"
"#update_t1:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(9, 9, 9, 255), stop:0.5 rgba(65, 65, 65, 255), stop:1 rgba(9, 9, 9, 255));\n"
"font: 75 8pt \"Square721 BT\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"border-width:1px;\n"
"border-style:inset;\n"
"border-top-color: rgb(72, 72, 72);\n"
"border-right-color:rgb(106, 106, 106);\n"
"border-bottom-color: rgb(106, 106, 106);\n"
"border-left-color: rgb(72, 72, 72);\n"
"}\n"
"\n"
"#abutton_3:!pressed,#rbutton_3:!pressed,#sbutton_3:!pressed{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(47, 47, 47, 255), stop:0.329545 rgba(72, 72, 72, 255), stop:1 rgba(47, 47, 47, 255));\n"
"font: 75 8pt \"Square721 BT\";\n"
"color:rgb(255, 255, 255);\n"
"\n"
"border-radius:10px;\n"
"border-width:1px;\n"
"border-style:inset;\n"
"border-top-color: rgb(72, 72, 72);\n"
"border-right-color:rgb(106, 106, 106);\n"
"border-bottom-color: rgb(76, 76, 76);\n"
"border-left-color: rgb(72, 72, 72);\n"
"}\n"
"#abutton_3:pressed,#rbutton_3:pressed,#sbutton_3:pressed{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(68, 68, 68, 255), stop:0.494318 rgba(106, 106, 106, 255), stop:1 rgba(63, 63, 63, 255));\n"
"font: 75 8pt \"Square721 BT\";\n"
"color: rgb(200, 200, 200);\n"
"border-radius:10px;\n"
"border-width:1px;\n"
"border-style:inset;\n"
"border-top-color: rgb(72, 72, 72);\n"
"border-right-color:rgb(106, 106, 106);\n"
"border-bottom-color: rgb(106, 106, 106);\n"
"border-left-color: rgb(72, 72, 72);\n"
"}\n"
"#abutton_3:hover,#rbutton_3:hover, #sbutton_3:hover{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(52, 52, 52, 255), stop:0.329545 rgba(90, 90, 90, 255), stop:1 rgba(52, 52, 52, 255))\n"
"}")
        self.twidget.setObjectName("twidget")
        self.sbutton_3 = QtWidgets.QPushButton(self.twidget)
        self.sbutton_3.setGeometry(QtCore.QRect(270, 370, 111, 31))
        self.sbutton_3.setObjectName("sbutton_3")
        self.tabwidget_3 = QtWidgets.QTabWidget(self.twidget)
        self.tabwidget_3.setGeometry(QtCore.QRect(30, 50, 351, 291))
        self.tabwidget_3.setStyleSheet("")
        self.tabwidget_3.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabwidget_3.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabwidget_3.setElideMode(QtCore.Qt.ElideNone)
        self.tabwidget_3.setUsesScrollButtons(False)
        self.tabwidget_3.setDocumentMode(False)
        self.tabwidget_3.setTabsClosable(False)
        self.tabwidget_3.setMovable(True)
        self.tabwidget_3.setTabBarAutoHide(False)
        self.tabwidget_3.setObjectName("tabwidget_3")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.imgdef_3 = QtWidgets.QLabel(self.tab_3)
        self.imgdef_3.setGeometry(QtCore.QRect(0, 0, 351, 261))
        self.imgdef_3.setStyleSheet("background-color: rgb(164, 164, 164);")
        self.imgdef_3.setFrameShape(QtWidgets.QFrame.Box)
        self.imgdef_3.setLineWidth(1)
        self.imgdef_3.setText("")
        self.imgdef_3.setTextFormat(QtCore.Qt.PlainText)
        self.imgdef_3.setScaledContents(True)
        self.imgdef_3.setAlignment(QtCore.Qt.AlignCenter)
        self.imgdef_3.setObjectName("imgdef_3")
        self.tabwidget_3.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.imgfilt_3 = QtWidgets.QLabel(self.tab_4)
        self.imgfilt_3.setGeometry(QtCore.QRect(0, 0, 351, 261))
        self.imgfilt_3.setStyleSheet("background-color: rgb(164, 164, 164);")
        self.imgfilt_3.setFrameShape(QtWidgets.QFrame.Box)
        self.imgfilt_3.setLineWidth(1)
        self.imgfilt_3.setText("")
        self.imgfilt_3.setTextFormat(QtCore.Qt.PlainText)
        self.imgfilt_3.setScaledContents(True)
        self.imgfilt_3.setAlignment(QtCore.Qt.AlignCenter)
        self.imgfilt_3.setWordWrap(False)
        self.imgfilt_3.setObjectName("imgfilt_3")
        self.tabwidget_3.addTab(self.tab_4, "Imagen Filtrada")
        self.rbutton_3 = QtWidgets.QPushButton(self.twidget)
        self.rbutton_3.setGeometry(QtCore.QRect(150, 370, 111, 31))
        self.rbutton_3.setObjectName("rbutton_3")
        self.l21 = QtWidgets.QLabel(self.twidget)
        self.l21.setGeometry(QtCore.QRect(420, 40, 151, 41))
        self.l21.setStyleSheet("")
        self.l21.setFrameShape(QtWidgets.QFrame.Box)
        self.l21.setLineWidth(1)
        self.l21.setTextFormat(QtCore.Qt.PlainText)
        self.l21.setAlignment(QtCore.Qt.AlignCenter)
        self.l21.setObjectName("l21")
        self.update_t1 = QtWidgets.QPushButton(self.twidget)
        self.update_t1.setGeometry(QtCore.QRect(580, 140, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Square721 BT")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.update_t1.setFont(font)
        self.update_t1.setStyleSheet("")
        self.update_t1.setDefault(False)
        self.update_t1.setFlat(False)
        self.update_t1.setObjectName("update_t1")
        self.abutton_3 = QtWidgets.QPushButton(self.twidget)
        self.abutton_3.setGeometry(QtCore.QRect(30, 370, 111, 31))
        self.abutton_3.setObjectName("abutton_3")
        self.label_E1_20 = QtWidgets.QLabel(self.twidget)
        self.label_E1_20.setGeometry(QtCore.QRect(450, 70, 411, 151))
        self.label_E1_20.setStyleSheet("background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(86, 86, 86, 255), stop:0.267045 rgba(60, 60, 60, 255), stop:0.596591 rgba(75, 75, 75, 255), stop:1 rgba(29, 29, 29, 255));\n"
"\n"
"border-style:outset;\n"
"border-width: 1px;\n"
"border-top-color:rgb(65, 65, 65);\n"
"border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(44, 44, 44, 255), stop:0.590909 rgba(95, 95, 95, 255), stop:1 rgba(45, 45, 45, 255));\n"
"border-bottom-color:transparent;\n"
"border-left-color: transparent;\n"
"\n"
"border-bottom-left-radius:30px;\n"
"border-top-right-radius:30px;")
        self.label_E1_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_E1_20.setLineWidth(1)
        self.label_E1_20.setText("")
        self.label_E1_20.setTextFormat(QtCore.Qt.PlainText)
        self.label_E1_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_E1_20.setObjectName("label_E1_20")
        self.label_13 = QtWidgets.QLabel(self.twidget)
        self.label_13.setGeometry(QtCore.QRect(470, 70, 391, 81))
        self.label_13.setStyleSheet("font: 75 10pt \"Square721 BT\";\n"
"color: rgb(255, 255, 255);")
        self.label_13.setTextFormat(QtCore.Qt.PlainText)
        self.label_13.setObjectName("label_13")
        self.label_E1_20.raise_()
        self.tabwidget_3.raise_()
        self.sbutton_3.raise_()
        self.rbutton_3.raise_()
        self.update_t1.raise_()
        self.abutton_3.raise_()
        self.l21.raise_()
        self.label_13.raise_()
        self.kwidget.raise_()
        self.twidget.raise_()
        self.fwidget.raise_()
        self.hwidget.raise_()
        self.line.raise_()
        self.hmenu.raise_()
        self.kmenu.raise_()
        self.fmenu.raise_()
        self.close.raise_()
        self.tmenu.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabwidget_2.setCurrentIndex(0)
        self.tabwidget.setCurrentIndex(0)
        self.tabwidget_3.setCurrentIndex(0)
        self.hmenu.clicked.connect(self.hwidget.show)
        self.kmenu.clicked.connect(self.hwidget.hide)
        self.fmenu.clicked.connect(self.hwidget.hide)
        self.hmenu.clicked.connect(self.fwidget.hide)
        self.fmenu.clicked.connect(self.fwidget.show)
        self.kmenu.clicked.connect(self.fwidget.hide)
        self.hmenu.clicked.connect(self.kwidget.hide)
        self.kmenu.clicked.connect(self.kwidget.show)
        self.fmenu.clicked.connect(self.kwidget.hide)
        self.close.clicked.connect(MainWindow.close)
        self.hmenu.clicked.connect(self.twidget.hide)
        self.kmenu.clicked.connect(self.twidget.hide)
        self.fmenu.clicked.connect(self.twidget.hide)
        self.tmenu.clicked.connect(self.twidget.show)
        self.tmenu.clicked.connect(self.fwidget.hide)
        self.tmenu.clicked.connect(self.hwidget.hide)
        self.tmenu.clicked.connect(self.kwidget.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_20.setToolTip(_translate("MainWindow", "wew"))
        self.label.setText(_translate("MainWindow", "Integrantes"))
        self.label_2.setText(_translate("MainWindow", "Cabrera Gallardo Carlos Gabriel"))
        self.label_3.setText(_translate("MainWindow", "Huamán Huamán William Fabián"))
        self.label_4.setText(_translate("MainWindow", "Rocha Montoya Carlos Adrián"))
        self.label_15.setText(_translate("MainWindow", "UNIVERSIDAD NACIONAL\n"
"        DE TRUJILLO"))
        self.l10.setText(_translate("MainWindow", "FILTRADO EN EL ESPACIO"))
        self.l20.setText(_translate("MainWindow", "FILTRADO EN LA FRECUENCIA"))
        self.label_7.setText(_translate("MainWindow", "Se aplica el kernel a cada pixel\n"
"de la imagen para suavizar,\n"
"realzar bordes, etc.\n"
"\n"
"Kernel para suavizado:"))
        self.label_8.setText(_translate("MainWindow", "Se modifican los componentes\n"
"de alta y baja frecuencia de la\n"
"imagen.\n"
"\n"
"Función para Filtros Pasa-Bajos:"))
        self.matrizLabel_3.setText(_translate("MainWindow", "┌                ┐\n"
"│1/5  ,1/5  ,1/5 │\n"
"│1/5  ,1/5  ,1/5 │\n"
"│1/5  ,1/5  ,1/5 │\n"
"└                ┘"))
        self.matrizLabel_4.setText(_translate("MainWindow", "cv2.GaussianBlur(image, \n"
"(5, 5), sigmaX=2)"))
        self.kmenu.setText(_translate("MainWindow", "Kernel"))
        self.fmenu.setText(_translate("MainWindow", "Filters"))
        self.hmenu.setText(_translate("MainWindow", "Home"))
        self.tabwidget_2.setTabText(self.tabwidget_2.indexOf(self.tab_7), _translate("MainWindow", "Imagen Original"))
        self.l5.setText(_translate("MainWindow", "FILTRO A USAR"))
        self.sbutton_2.setText(_translate("MainWindow", "GUARDAR"))
        self.rbutton_2.setText(_translate("MainWindow", "REINICIAR"))
        self.update_f.setText(_translate("MainWindow", "ACTUALIZAR GRÁFICO"))
        self.combo_2.setItemText(0, _translate("MainWindow", "Filtro Pasa-bajos Gaussiano"))
        self.combo_2.setItemText(1, _translate("MainWindow", "Filtro Pasa-altos Gaussiano"))
        self.combo_2.setItemText(2, _translate("MainWindow", "Filtro Laplaciano"))
        self.combo_2.setItemText(3, _translate("MainWindow", "Filtro Highboost"))
        self.combo_2.setItemText(4, _translate("MainWindow", "Filtro de Enfatizado"))
        self.combo_2.setItemText(5, _translate("MainWindow", "Filtro Homomórfico"))
        self.abutton_2.setText(_translate("MainWindow", "ABRIR"))
        self.sbutton.setText(_translate("MainWindow", "GUARDAR"))
        self.lineedit.setPlaceholderText(_translate("MainWindow", "MATRIZ TIPO: [1, 2, 3 ;1, 2, 3 ;1, 2, 3]"))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab_1), _translate("MainWindow", "Imagen Original"))
        self.rbutton.setText(_translate("MainWindow", "REINICIAR"))
        self.l1.setText(_translate("MainWindow", "MATRIZ EMPLEADA"))
        self.update_p.setText(_translate("MainWindow", "ACTUALIZAR GRÁFICO"))
        self.combo.setItemText(0, _translate("MainWindow", "Kernel de suavizado"))
        self.combo.setItemText(1, _translate("MainWindow", "Kernel de enfoque"))
        self.combo.setItemText(2, _translate("MainWindow", "Kernel de detección de bordes"))
        self.combo.setItemText(3, _translate("MainWindow", "Kernel de enriquecimiento"))
        self.combo.setItemText(4, _translate("MainWindow", "Kernel de embossing"))
        self.update_d.setText(_translate("MainWindow", "ACTUALIZAR GRÁFICO"))
        self.matrizLabel.setText(_translate("MainWindow", "┌                        ┐\n"
"│1.      1.      1.      │\n"
"│1.      1.      1.      │\n"
"│1.      1.      1.      │\n"
"└                        ┘"))
        self.l2.setText(_translate("MainWindow", "PERSONALIZABLE"))
        self.l3.setText(_translate("MainWindow", "POR DEFECTO"))
        self.abutton.setText(_translate("MainWindow", "ABRIR"))
        self.close.setText(_translate("MainWindow", "X"))
        self.tmenu.setText(_translate("MainWindow", "Test"))
        self.sbutton_3.setText(_translate("MainWindow", "GUARDAR"))
        self.tabwidget_3.setTabText(self.tabwidget_3.indexOf(self.tab_3), _translate("MainWindow", "Imagen Original"))
        self.rbutton_3.setText(_translate("MainWindow", "REINICIAR"))
        self.l21.setText(_translate("MainWindow", "ESPECTRO"))
        self.update_t1.setText(_translate("MainWindow", "ACTUALIZAR GRÁFICO"))
        self.abutton_3.setText(_translate("MainWindow", "ABRIR"))
        self.label_13.setText(_translate("MainWindow", "Sirve para obtener el espectro de una imagen en una\n"
"librería de OpenCV."))
